
#ifndef __DEBICT_MECANUMBOT_CONTROLLER__MECANUMBOT_CONTROLLER_COMPILER_H__
#define __DEBICT_MECANUMBOT_CONTROLLER__MECANUMBOT_CONTROLLER_COMPILER_H__

#define DEBICT_MECANUMBOT_CONTROLLER_EXPORT __attribute__((visibility("default")))
#define DEBICT_MECANUMBOT_CONTROLLER_IMPORT

#define DEBICT_MECANUMBOT_CONTROLLER_PUBLIC __attribute__((visibility("default")))
#define DEBICT_MECANUMBOT_CONTROLLER_LOCAL __attribute__((visibility("hidden")))

#define DEBICT_MECANUMBOT_CONTROLLER_PUBLIC_TYPE

#endif // __DEBICT_MECANUMBOT_CONTROLLER__MECANUMBOT_CONTROLLER_COMPILER_H__