teleop:
  ros__parameters:
    # Utilisation de la manette de jeu
    joy_topic: /joy
    twist_topic: /cmd_vel
    move:
      forward:
        axis: 1
        scale: 3.5
        deadzone: 0.0
      reverse:
        axis: 1
        scale: -3.5  # Inverser l'échelle pour la marche arrière
        deadzone: 0.0
      left:
        axis: 0
        scale: 3.5
        deadzone: 0.0
      right:
        axis: 0
        scale: -3.5  # Inverser l'échelle pour tourner à droite
        deadzone: 0.0
    turn:
      left:
        axis: 5
        scale: 10.0
        deadzone: 0.0
        offset: 1.0
      right:
        axis: 4
        scale: -10.0
        deadzone: 0.0
        offset: 1.0

  # Nouvelles configurations pour le clavier
  keyboard:
    twist_topic: /cmd_vel
    move:
      forward:
        key: 'z'
        scale: 1.0
      reverse:
        key: 's'
        scale: -1.0  # Inverser l'échelle pour la marche arrière
      left:
        key: 'q'
        scale: 1.0
      right:
        key: 'd'
        scale: -1.0  # Inverser l'échelle pour tourner à droite
    turn:
      left:
        key: 'a'
        scale: 1.0
      right:
        key: 'e'
        scale: -1.0  # Inverser l'échelle pour tourner à droite

joystick:
  ros__parameters:
    # Utilisation de la manette de jeu
    joy_topic: /joy
    dev: /dev/input/js0
    deadzone: 0.2
